### PR TITLE
Some issues spotted

### PR DESCRIPTION
**Pull request by ordian**
This PR lists some issues and suggested fixes for them (feel free to pick them up separately and close this PR):

In addition to issues outlined in https://github.com/paritytech/zombienet-sdk/issues/117#issuecomment-1867941395,
here are some issues spotted when writing https://github.com/paritytech/disabling-e2e-tests:
- runtime genesis patch is applied incorrectly (extra `/genesis` pointer shouldn't be added)
- malus accepts [subcommands](https://github.com/paritytech/polkadot-sdk/blob/4c0e0e071355c1048d75fba538c96c35ac743547/polkadot/zombienet_tests/functional/0008-dispute-old-finalized.toml#L25), having a command with spaces not supported, so I added a subcommand support
- some types need to be exported in order to be able to reuse setup/helper functions across multiple tests
- test cleanup doesn't always work (zombie polkadot processes - not fixed here)

### CODE REVIEW

**Review by pepoviola — COMMENTED** [review]
Looks great!! Thanks @ordian! Does make sense to have a "subcommand" machinery, since this is in reality the first argument. We can also explore allow spaces in the command, but I think make more sense to move the subcommand to be the first argument. Wdyt?

**Comment by ordian** [comment]
> Looks great!! Thanks @ordian! Does make sense to have a "subcommand" machinery, since this is in reality the first argument. We can also explore allow spaces in the command, but I think make more sense to move the subcommand to be the first argument. Wdyt?

Thanks for the quick reply :)

Yes, this is how subcommand is implemented - as the first argument: https://github.com/paritytech/zombienet-sdk/pull/145/files#diff-649752b713d3c65989f2b05ad304ea739c215a93b743ade5104b08ed6211bef7. I think this is the way to go.

**Comment by pepoviola** [comment]
> > Looks great!! Thanks @ordian! Does make sense to have a "subcommand" machinery, since this is in reality the first argument. We can also explore allow spaces in the command, but I think make more sense to move the subcommand to be the first argument. Wdyt?
> 
> Thanks for the quick reply :)
> 
> Yes, this is how subcommand is implemented - as the first argument: https://github.com/paritytech/zombienet-sdk/pull/145/files#diff-649752b713d3c65989f2b05ad304ea739c215a93b743ade5104b08ed6211bef7. I think this is the way to go.

Oks, so we should add some docs to indicate that the `subcommand` can be set only at `config` level but will be used as first argument for the `node cmd`, again thanks for the feedback and looks great!

**Comment by pepoviola** [comment]
Hi @ordian, again thanks for your feedback. Did you think will be useful to have a `test-utils` crate with fns like `wait_for_block`/`wait_for_metric` or other testing related assertions? Also, those should allow to have a timeout error.

Thx!

**Comment by ordian** [comment]
> Hi @ordian, again thanks for your feedback. Did you think will be useful to have a `test-utils` crate with fns like `wait_for_block`/`wait_for_metric` or other testing related assertions? Also, those should allow to have a timeout error.
> 
> Thx!

Hey hey, long term this might be a good idea. I don't know what would be the most ergonomic API, could be simply a method like node.wait_for_block(2), or a trait extension. 
> Also, those should allow to have a timeout error.

This is debatable. We could avoid having timeouts on individual function and just have one global timeout on a test (e.g. an [attribute macro](https://docs.rs/ntest/latest/ntest/attr.timeout.html)).

This is not needed in the short-term, better to experiment with/get feedback on the core API first and stabilize it and then we can start adding these nice amenities.

**Comment by pepoviola** [comment]
Hey @ordian, did you think this one is ready for review/merge? 
Thx!

**Comment by ordian** [comment]
Hey @pepoviola, yeah, I can address any feedback here or feel free to close this and address issues individually by cherry-picking commits.

**Review by pepoviola — APPROVED** [review]

**Pull request merged**
